name: Nix (Update Inputs)

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  update:
    if: github.repository == 'hyprwm/Hyprland'
    name: inputs
    runs-on: ${{ fromJSON((github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && vars.LOCAL_RUNNER_LABELS || '["ubuntu-latest"]') }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: hyprwm/actions/nix-setup@main

      - name: Update inputs
        run: nix/update-inputs.sh

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[gha] Nix: update inputs"
